In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from darknet.feat_select import *

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import export_graphviz
from sklearn.tree import plot_tree

In [5]:
random_state = 42
dataset_folder = "dataset/" 
img_folder = "imgs/"

np.random.seed(random_state)
plt.rcParams['figure.figsize'] = (18,6)
plt.rcParams["savefig.format"] = 'pdf'
plt.rcParams["savefig.dpi"] = 600
plt.rcParams.update({'font.size': 18})

In [6]:
samples_detec = pd.read_csv( r"C:\Users\sreek\Desktop\PROJECTS\mini project\dataset\darknet_dataset_processed.csv")
del samples_detec['Label.1']
samples_detec.head()

Flow ID         Src IP  Src Port  \
0     10.152.152.11-216.58.220.99-57158-443-6  10.152.152.11     57158   
1     10.152.152.11-216.58.220.99-57159-443-6  10.152.152.11     57159   
2     10.152.152.11-216.58.220.99-57160-443-6  10.152.152.11     57160   
3    10.152.152.11-74.125.136.120-49134-443-6  10.152.152.11     49134   
4  10.152.152.11-173.194.65.127-34697-19305-6  10.152.152.11     34697   

           Dst IP  Dst Port  Protocol               Timestamp  Flow Duration  \
0   216.58.220.99       443         6  24/07/2015 04:09:48 PM          229.0   
1   216.58.220.99       443         6  24/07/2015 04:09:48 PM          407.0   
2   216.58.220.99       443         6  24/07/2015 04:09:48 PM          431.0   
3  74.125.136.120       443         6  24/07/2015 04:09:48 PM          359.0   
4  173.194.65.127     19305         6  24/07/2015 04:09:45 PM     10778451.0   

   Total Fwd Packet  Total Bwd packets  ...  src_ip_1gram  src_ip_2gram  \
0               1.0                1.0  ...            10        10 152   
1               1.0                1.0  ...            10        10 152   
2               1.0                1.0  ...            10        10 152   
3               1.0                1.0  ...            10        10 152   
4             591.0              400.0  ...            10        10 152   

   src_ip_3gram  dst_ip_1gram  dst_ip_2gram  dst_ip_3gram  src_ip_country  \
0    10 152 152           216        216 58    216 58 220             NaN   
1    10 152 152           216        216 58    216 58 220             NaN   
2    10 152 152           216        216 58    216 58 220             NaN   
3    10 152 152            74        74 125    74 125 136             NaN   
4    10 152 152           173       173 194    173 194 65             NaN   

   dst_ip_country  src_bogon  dst_bogon  
0              US       True      False  
1              US       True      False  
2              US       True      False  
3              US       True      False  
4              US       True      False  

[5 rows x 95 columns]

In [7]:
samples_app = pd.read_csv( r"C:\Users\sreek\Desktop\PROJECTS\mini project\dataset\darknet_dataset_processed_encoded.csv")
samples_app = samples_app[samples_app['Label'] == 'Darknet']
del samples_app['Label']
samples_app.head()

col_0  col_1  col_2  col_3  col_4  col_5  col_6  col_7  col_8  col_9  \
117170      0      0      0      0      0      0      0      0      0      0   
117171      0      0      0      0      0      0      0      0      0      0   
117172      0      0      0      0      0      0      0      0      0      0   
117173      0      0      0      0      0      0      0      0      0      0   
117174      0      0      0      0      0      0      0      0      0      0   

        ...  Fwd Seg Size Min  Active Mean  Active Std  Active Max  \
117170  ...          0.589647            0           0           0   
117171  ...          0.589647            0           0           0   
117172  ...          0.589647            0           0           0   
117173  ...          0.589647            0           0           0   
117174  ...          0.589647            0           0           0   

        Active Min     Idle Mean      Idle Std      Idle Max      Idle Min  \
117170           0  1.456330e+15  3.683488e+07  1.456330e+15  1.456330e+15   
117171           0  1.456330e+15  3.558961e+07  1.456330e+15  1.456330e+15   
117172           0  1.456330e+15  3.301057e+07  1.456330e+15  1.456330e+15   
117173           0  1.456330e+15  5.227810e+05  1.456330e+15  1.456330e+15   
117174           0  1.456330e+15  1.052330e+05  1.456330e+15  1.456330e+15   

                Label.1  
117170  Audio-Streaming  
117171  Audio-Streaming  
117172  Audio-Streaming  
117173  Audio-Streaming  
117174  Audio-Streaming  

[5 rows x 185 columns]

In [8]:
X, y, labels = split_train_target(samples_detec, "Label")
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33)
columns = samples_detec.columns.tolist()

In [14]:
dt = DecisionTreeClassifier()
rfe_dt = select_features_rfecv(dt, X, y, 1, step=1)

ValueError: Shape of passed values is (141481, 94), indices imply (141481, 3)

In [10]:
final_report_dt = final_evaluation_rfe(dt, X, y, labels, rfe_dt)
print()
print(f"Optimal number of features: {rfe_dt.n_features_}")
selected_columns_dt = summarize_feats(rfe_dt, dt, columns)

NameError: name 'rfe_dt' is not defined

In [17]:
dotfile = open("dtree3.dot", 'w')
export_graphviz(dt, out_file = dotfile, feature_names = selected_columns_dt)
dotfile.close()

NameError: name 'selected_columns_dt' is not defined

In [15]:
rf = RandomForestClassifier()
rfe_rf = select_features_rfecv(rf, X, y, 1, step=1)

ValueError: could not convert string to float: '10.152.152.11-216.58.220.99-57158-443-6'

In [16]:
final_report_rf = final_evaluation_rfe(rf, X, y, labels, rfe_rf)
print()
print(f"Optimal number of features: {rfe_rf.n_features_}")
selected_columns_rf = summarize_feats(rfe_rf, rf, columns)

NameError: name 'rfe_rf' is not defined

# Darknet traffic caracterization

In [17]:
X1, y1, labels1 = split_train_target(samples_app, "Label.1")
X1_train, X1_test, y1_train, y1_test = train_test_split(X1, y1, test_size=0.33, random_state=random_state)
columns1 = samples_app.columns.tolist()

## Decision tree

In [18]:
dt1 = DecisionTreeClassifier(random_state=random_state)
rfe_dt1 = select_features_rfecv(dt1, X1, y1, 1, step=1)

Fitting estimator with 184 features.
Fitting estimator with 183 features.
Fitting estimator with 182 features.
Fitting estimator with 181 features.
Fitting estimator with 180 features.
Fitting estimator with 179 features.
Fitting estimator with 178 features.
Fitting estimator with 177 features.
Fitting estimator with 176 features.
Fitting estimator with 175 features.
Fitting estimator with 174 features.
Fitting estimator with 173 features.
Fitting estimator with 172 features.
Fitting estimator with 171 features.
Fitting estimator with 170 features.
Fitting estimator with 169 features.
Fitting estimator with 168 features.
Fitting estimator with 167 features.
Fitting estimator with 166 features.
Fitting estimator with 165 features.
Fitting estimator with 164 features.
Fitting estimator with 163 features.
Fitting estimator with 162 features.
Fitting estimator with 161 features.
Fitting estimator with 160 features.
Fitting estimator with 159 features.
Fitting estimator with 158 features.
F

In [20]:
final_evaluation_rfe(dt1, X1, y1, labels1, rfe_dt1)
print()
print(f"Optimal number of features: {rfe_dt1.n_features_}")
selected_columns_dt1 = summarize_feats(rfe_dt1, dt1, columns1)

NameError: name 'fname' is not defined

In [ ]:
dotfile = open("dtree2.dot", 'w')
export_graphviz(dt1, out_file = dotfile, feature_names = selected_columns_dt1)
dotfile.close()

## Random forest

In [ ]:
rf1 = RandomForestClassifier(random_state=random_state)
rfe_rf1 = select_features_rfecv(rf1, X1, y1, 1, step=1)

Fitting estimator with 184 features.
Fitting estimator with 183 features.
Fitting estimator with 182 features.
Fitting estimator with 181 features.
Fitting estimator with 180 features.
Fitting estimator with 179 features.
Fitting estimator with 178 features.
Fitting estimator with 177 features.
Fitting estimator with 176 features.
Fitting estimator with 175 features.
Fitting estimator with 174 features.
Fitting estimator with 173 features.
Fitting estimator with 172 features.
Fitting estimator with 171 features.
Fitting estimator with 170 features.
Fitting estimator with 169 features.
Fitting estimator with 168 features.
Fitting estimator with 167 features.
Fitting estimator with 166 features.
Fitting estimator with 165 features.
Fitting estimator with 164 features.
Fitting estimator with 163 features.
Fitting estimator with 162 features.
Fitting estimator with 161 features.
Fitting estimator with 160 features.
Fitting estimator with 159 features.
Fitting estimator with 158 features.
F

In [ ]:
final_report_rf1 = final_evaluation_rfe(rf1, X1, y1, labels1, rfe_rf1)
print()
print(f"\nOptimal number of features: {rfe_rf1.n_features_}")
selected_columns_rf1 = summarize_feats(rfe_rf1, rf1, columns1)

100%|██████████| 10/10 [00:28<00:00,  2.87s/it]


               precision       recall       f1-score       support       
Audio-Streaming:  99.79		99.53		99.66		88830.00		
Browsing:         90.76		89.08		89.68		1750.00		
Chat:             99.25		99.54		99.39		30520.00		
Email:            96.79		96.46		96.56		3930.00		
File-Transfer:    98.17		98.38		98.27		17300.00		
P2P:              95.55		98.12		96.66		1570.00		
VOIP:             97.91		97.87		97.87		9860.00		
Video-Streaming:  96.13		97.04		96.57		9120.00		


 10-fold Accuracy: 98.97%
Test accuracy: 98.95%


Confusion matrix:
[[4377    3   13    0    3    1    3    1]
 [   3   79    3    0    1    0    1    1]
 [   7    3 1476    0    2    0    0    1]
 [   0    0    0  187    2    0    0    0]
 [   0    0    0    7  867    0    0    6]
 [   0    2    0    0    0   61    0    0]
 [   0    0    0    0    0    0  471    8]
 [   0    0    0    0    4    0    9  421]]

Audio-Streaming :   99.77%
Browsing :          90.80%
Chat :              98.93%
Email :             96.39%
File-Tr